# -*- python -*-
Import("env")

basicLibs = "daf_base daf_data pex_exceptions pex_logging pex_policy".split()
env.Program(["lsstdata01.cc"], LIBS=env.libs["boost"] + basicLibs)

env.CheckSwig("python", ilang="c++")
env.Append(SWIGFLAGS=" -Ipython")

#
# Tests
#
import lsst.tests

tests = lsst.tests.Control(env, verbose = True)
tests.run("lsstdata01.cc")

for target in tests.run("*.py"):
    env.Depends(target, exceptionTests)
    for mod in Split("utils daf_base daf_data pex_logging"):
        env.Depends(target,
                    "../python/lsst/daf/data/_%s%s" % (mod, env['LDMODULESUFFIX']))
