# -*- python -*-
Import('env')
import os

env.SharedLibrary('daf_data',
                         map(lambda str: "../src/data/" + str,
                            ["Citizen.cc",
                             "DataProperty.cc",
                             "DataPropertyFormatter.cc",
                             "FitsFormatter.cc",
                             "LsstDataConfigurator.cc",
                             "LsstImpl_DC2.cc",
                             "Provenance.cc",
                             "ReleaseProcess.cc",
                             "Security.cc",
                             "SupportFactory.cc"
                            ]), LIBS=env.getlibs("boost jaula coral seal mysqlclient"))

