# -*- python -*-
Import('env')
import os

basicLibs = "daf_base daf_data pex_exceptions pex_logging pex_policy".split()
env.SharedLibrary('daf_data',
                         map(lambda str: "../src/data/" + str,
                            ["DataPropertyFormatter.cc",
                             "FitsFormatter.cc",
                             "LsstDataConfigurator.cc",
                             "LsstImpl_DC2.cc",
                             "Provenance.cc",
                             "ReleaseProcess.cc",
                             "Security.cc",
                             "SupportFactory.cc"
                            ]), LIBS=env.getlibs("boost") + basicLibs)

