# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils pex_exceptions daf_base pex_logging pex_policy daf_persistence security")
env.LoadableModuleIncomplete("_dataLib", Split("dataLib.i"), LIBS=env.getlibs(env["eups_product"]))
