# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_policy daf_persistence security")
env.LoadableModuleIncomplete("_dataLib", Split("dataLib.i"),
                             LIBS=env.getlibs("boost utils daf_base daf_data pex_exceptions pex_logging pex_policy security"))
